% load in preprocessed surface generated by Conn Toolbox
func_path = '/projectnb/somerslab/tom/projects/spacetime_network/data/unpacked_data_nii/MM/func/run10/sausub-MM_run10_spacetime.surf.nii';
func_data = MRIread(func_path);% load in preprocessed surface generated by Conn Toolbox
func_path = '/projectnb/somerslab/tom/projects/spacetime_network/data/unpacked_data_nii/MM/func/run10/sausub-MM_run10_spacetime.surf.nii';
func_data = MRIread(func_path);
func_vol = func_data.vol;

% % % % Transform into fsaverage format
% % % dim_size = 42*83*94;
% % % func_vol_1d = reshape(func_vol, dim_size, 260);
% % % func_vol_1d_lh = func_vol_1d(1:dim_size/2,:);
% % % func_vol_1d_rh = func_vol_1d((dim_size/2)+1:end,:);
% % % 
% % % dummy_data = MRIread('/projectnb/somerslab/tom/projects/spacetime_network/data/recons/fsaverage/label/lDummy.nii.gz');
% % % dummy_data.volsize = [size(func_vol_1d_lh) 1];
% % % % Write to nifti
% % % dummy_data.vol = func_vol_1d_lh;
% % % MRIwrite(dummy_data, 'db_test_lh_run10_MM.nii.gz', 'double')



originalMatrix=func_vol;
% Assume originalMatrix is your 42x83x94x260 matrix.
originalSize = size(originalMatrix); % Gets the size of the original matrix.

% Reshape the matrix into a (42*83*94)x260 matrix.
% This step combines the first three dimensions while keeping the last dimension separate.
reshapedMatrix = reshape(originalMatrix, prod(originalSize(1:3)), originalSize(4));

% Now, split the reshaped matrix into two halves, each will be 163842x260.
% Since the total number of elements for the first three dimensions is 327684,
% dividing by 2 gives us 163842, which matches the target size for each vector.
halfSize = size(reshapedMatrix, 1) / 2;

% Extract each half of the reshaped matrix into the desired vectors.
% Each "vector" will be manipulated to have a shape of 1x163842x1x260.
vector1 = reshapedMatrix(1:halfSize, :);
vector2 = reshapedMatrix(halfSize+1:end, :);

% Reshape each vector to the desired shape.
vector1 = reshape(vector1, [1, halfSize, 1, originalSize(4)]);
vector2 = reshape(vector2, [1, halfSize, 1, originalSize(4)]);


%dummy_data = MRIread('/projectnb/somerslab/tom/projects/spacetime_network/data/recons/fsaverage/label/lDummy.nii.gz');

dummy_data = MRIread('/projectnb/somerslab/mri-fnirs/vols_wmLocalizer1Way/pp3p20/bold/014/fmc.sm0.self.lh.nii.gz');

dummy_data.vol = vector1;
MRIwrite(dummy_data, 'db_test_lh_run10_MM.nii', 'double')
dummy_data.vol = vector2;
MRIwrite(dummy_data, 'db_test_rh_run10_MM.nii', 'double')

