

% load in preprocessed surface generated by Conn Toolbox
func_path = '/projectnb/somerslab/tom/projects/spacetime_network/data/unpacked_data_nii/MM/func/run10/sausub-MM_run10_spacetime.surf.nii';
func_data = niftiread(func_path);

% Transform into fsaverage format
dim_size = 42*83*94;
func_data_1d = reshape(func_data, dim_size, 260);
func_data_1d_lh = func_data_1d(1:dim_size/2,:);
func_data_1d_lh_singleton(1,:,1,:) = func_data_1d_lh;
func_data_1d_rh = func_data_1d((dim_size/2)+1:end,:);
func_data_1d_rh_singleton(1,:,1,:) = func_data_1d_rh;

info = niftiinfo(func_path);
info.ImageSize = size(func_data_1d_lh_singleton);
info.raw.dim(2:5) = size(func_data_1d_lh_singleton);
% Write to nifti

niftiwrite(func_data_1d_lh_singleton, 'test_lh_run10_MM.nii', info)










% load in preprocessed surface generated by Conn Toolbox
func_path = '/projectnb/somerslab/tom/projects/spacetime_network/data/unpacked_data_nii/MM/func/run10/sausub-MM_run10_spacetime.surf.nii';
func_data = MRIread(func_path);% load in preprocessed surface generated by Conn Toolbox
func_path = '/projectnb/somerslab/tom/projects/spacetime_network/data/unpacked_data_nii/MM/func/run10/sausub-MM_run10_spacetime.surf.nii';
func_data = MRIread(func_path);
func_vol = func_data.vol;

% Transform into fsaverage format
dim_size = 42*83*94;
func_data_1d = reshape(func_vol, dim_size, 260);
func_data_1d_lh = func_data_1d(1:dim_size/2,:);
func_data_1d_lh_singleton(1,:,1,:) = func_data_1d_lh;
func_data_1d_rh = func_data_1d((dim_size/2)+1:end,:);
func_data_1d_rh_singleton(1,:,1,:) = func_data_1d_rh;

%dummy_data = MRIread('/projectnb/somerslab/tom/projects/spacetime_network/data/recons/fsaverage/label/lDummy.nii.gz');
%dummy_data.volsize = [size(func_vol_1d_lh) 1];

% Write to nifti
func_data.vol = func_data_1d_lh_singleton;
MRIwrite(func_data, 'test_lh_run10_MM.nii', 'double')

